export type Data = Record<string, unknown>;
export type Currency = 'USD' | 'KRW';
export type Role = 'champion' | 'candidate' | 'trading-moe';
export interface Decision {symbol?:string;action?:string;date?:string;as_of?:string;role?:string;target_weight?:number;current_weight?:number;cash_weight?:number;value?:number;seconds?:number}
export interface Position {symbol:string;quantity:number|string;average_cost:number|string;mark?:number;value?:number;weight?:number;unrealized_pnl?:number}
export interface Book {initial_cash?:number;cash?:number;equity?:number;net_pnl?:number;net_return_rate?:number;holdings_value?:number;fees?:number;slippage?:number;spread?:number;sell_tax?:number;costs?:number;realized_pnl?:number;unrealized_pnl?:number;trade_count?:number;positions?:Position[]|Record<string,Omit<Position,'symbol'>>;marks?:Record<string,number>}
export interface Fill {date?:string;symbol:string;currency?:Currency;action?:string;quantity?:number;price?:number;fee?:number;realized_pnl?:number}
export interface Replay {total?:number;eligible?:number;untrained?:number;remaining_for_update?:number;pending?:number;quarantined?:number;unsupported?:number;bytes?:number;awaiting_checkpoint?:number;storage_pressure?:boolean;blocked_reasons?:Record<string,number>;daily?:{day:string;enqueued?:number;completed?:number;remaining?:number;blocked?:number}[]}
export interface EvidenceCache {available?:boolean;error?:string;market_outputs?:number;stored_outputs?:number;stored_decisions?:number;cycles?:number;bytes?:number;latest_as_of?:string|null}
export interface Model {cache?:EvidenceCache;updated_at?:string;status?:string;requested?:boolean;loaded?:boolean;alive?:boolean;stop_requested?:boolean;pid?:number|null;error?:string|null;message?:string;source?:string;source_kind?:string;account_scope?:string;checkpoint?:string;checkpoint_bytes?:number;parameters?:number;expert_count?:number;load_count?:number;ram_weight_bytes?:number;gpu_weight_bytes?:number;worker_ram_bytes?:number;compute_device?:string|null;last_decision?:string;decision_seconds?:number;decision?:Decision;cycle_seconds?:number;market_timestamp?:string;optimizer_updates?:number;applied_replay_rows?:number;learning_active?:boolean;learning?:{loss?:number;reward_points?:number;updated_at?:string;samples?:number;seconds?:number};replay?:Replay;books?:Partial<Record<Currency,Book>>;fills?:Fill[];reward_points?:Partial<Record<Currency,number>>;stages?:Record<string,boolean>;evaluation_stage?:string;selected_experts?:string[];gpu_waiting?:boolean;gpu_wait_seconds?:number;compute?:{inference_device?:string;learning_device?:string;gpu_name?:string;allocated_bytes?:number;reserved_bytes?:number;expert_gpu_limit?:number}}
export interface Account {books?:Partial<Record<Currency,Book>>;recent_fills?:Fill[];pending_orders?:unknown;account_scope?:string}
export interface Instrument {symbol:string;name?:string;market?:string;group?:string;asset_class?:string;fresh?:boolean;quote?:Record<string,string|number>|null;decision?:Decision|null;interval?:string;refresh_seconds?:number}
export interface SystemStatus {status_updated_at?:string;running?:boolean;feed_running?:boolean;stopping?:boolean;restarting?:boolean;mode?:string;horizon?:string;autonomy_enabled?:boolean;observe_enabled?:boolean;paper_enabled?:boolean;learning_enabled?:boolean;real_orders_enabled?:boolean;configured_instruments?:number;feed_rows?:number;model_runtime?:Partial<Record<'champion'|'candidate',Model>>;account_observability?:Partial<Record<'champion'|'candidate',Account>>;instruments?:Instrument[];decisions?:Decision[];physical_gpu?:{utilization_percent?:number;memory_used_mb?:number;memory_total_mb?:number};feed_metrics?:Data;learning?:Data;metrics?:Data;provider?:Data;logs?:string|string[];validation_comparison?:{status?:string;active?:boolean;bars_current?:number;bars_required?:number;reason?:string;scores?:Record<string,ScorePair>}}
export interface Score {initial_NAV?:number;final_NAV?:number;net_return?:number;pnl?:number;max_drawdown?:number;fees?:number;slippage?:number;trades?:number;decisions?:number;seconds?:number;first_as_of?:string;last_as_of?:string}
export interface ScorePair {champion?:Score;candidate?:Score;delta?:number}
export interface MutationOperation {kind:string;expert?:string;enabled?:boolean;field?:string;value?:number}
export interface Recipe {candidate_id?:string;parent_id?:string;enabled_experts?:string[];expert_roles?:Record<string,string>;symbol_applicability?:Record<string,string[]|null>;refresh_seconds?:Record<string,number>;market_routing?:{top_k?:number;temperature?:number};policy_routing?:{top_k?:number;temperature?:number};mutation_description?:string;mutation_operations?:MutationOperation[];generation_reason?:string;created_at?:string;evaluation_state?:string;reason?:string;scores?:Record<string,ScorePair>;base_checkpoint_hash?:string}
export interface AssemblyBuild {id?:string;status?:'idle'|'queued'|'running'|'ready'|'registered'|'error'|'cancelled';phase?:string;progress?:number;message?:string;path?:string;bytes?:number;created_at?:string;finished_at?:string;market_experts?:string[];action_experts?:string[];recipe?:Recipe;error?:string}
export interface Expert {id:string;name:string;role?:string;description?:string;eligible?:boolean;parameters?:number;dtype?:string;checkpoint_bytes?:number;weight_bytes?:number;ram_bytes?:number;vram_bytes?:number;location?:string;loaded?:boolean;active?:boolean;frozen?:boolean;router_selected?:boolean;last_inference_seconds?:number;last_used_at?:string;last_timings?:Record<string,number>;input_shapes?:unknown;output_shape?:unknown;last_input_shapes?:unknown;last_output_shape?:unknown;error?:string|null;license?:string;universe?:string[]|null}
export interface Registry {registered?:boolean;experts?:Expert[];totals?:Record<string,number>;updated_at?:string;unavailable?:{name:string;reason:string}[];pipeline?:Data;recent_error?:string|null}
export interface Assembly {enabled?:boolean;settings?:{auto_replace?:boolean;auto_promote?:boolean;detect_experts?:boolean};champion?:Recipe;candidate?:Recipe;queue?:Recipe[];history?:{time?:string;event?:string;candidate_id?:string;mutation?:string;reason?:string;scores?:Record<string,ScorePair>}[];experts?:Expert[];new_experts?:string[];worker?:Model;experiments?:number;promotions?:number;rejections?:number;trial_paused?:boolean;message?:string;evaluation_context?:{symbols?:string[]};candidate_state_bytes?:number;history_stats?:Data;build?:AssemblyBuild}
export interface Provider {provider?:string;provider_name?:string;environment?:string;saved?:boolean;has_app_key?:boolean;has_secret?:boolean;has_account?:boolean;last_test?:{ok?:boolean;time?:string;message?:string};vault_error?:string}
