import {useMemo,useState,type ReactNode} from 'react';
import {useReactTable,getCoreRowModel,getSortedRowModel,getFilteredRowModel,getPaginationRowModel,flexRender,type SortingState,type ColumnDef} from '@tanstack/react-table';
import {Button,Empty,inputClass} from './Primitives';
export interface Column<T>{key:string;label:string;render:(item:T)=>ReactNode;sort?:(item:T)=>string|number}
export function DataTable<T>({items,columns,label,keyFor,searchText,select}:{items:T[];columns:Column<T>[];label:string;keyFor:(item:T)=>string;searchText?:(item:T)=>string;select?:{checked:(item:T)=>boolean;toggle:(item:T)=>void;disabled?:(item:T)=>boolean}}){
 const [query,setQuery]=useState(''),[sorting,setSorting]=useState<SortingState>([]);
 const definitions=useMemo<ColumnDef<T>[]>(()=>columns.map(c=>({id:c.key,header:c.label,accessorFn:c.sort||keyFor,enableSorting:!!c.sort,cell:context=>c.render(context.row.original)})),[columns,keyFor]);
 const table=useReactTable({data:items,columns:definitions,getRowId:keyFor,state:{sorting,globalFilter:query},
 onSortingChange:setSorting,onGlobalFilterChange:setQuery,globalFilterFn:(row,_column,value)=>(searchText?.(row.original)||keyFor(row.original)).toLowerCase().includes(String(value).toLowerCase()),
 getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),initialState:{pagination:{pageSize:20}}});
 return <div><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><input aria-label={label+' 검색'} className={inputClass+' max-w-xs'} placeholder="이름·코드 검색" value={query} onChange={e=>{setQuery(e.target.value);table.setPageIndex(0)}}/><span className="text-xs text-slate-400">{table.getFilteredRowModel().rows.length}개 / 전체 {items.length}개</span></div>
 <div className="overflow-auto rounded-xl border border-slate-100"><table aria-label={label} className="w-full whitespace-nowrap text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-400">{table.getHeaderGroups().map(group=><tr key={group.id}>{select&&<th className="px-4 py-3">선택</th>}{group.headers.map(header=><th key={header.id} className="px-4 py-3 font-medium"><Button className="!bg-transparent !p-0 !text-xs !text-slate-500" disabled={!header.column.getCanSort()} onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header,header.getContext())}{header.column.getIsSorted()==='asc'?' ↑':header.column.getIsSorted()==='desc'?' ↓':''}</Button></th>)}</tr>)}</thead>
 <tbody>{table.getRowModel().rows.map(row=><tr key={row.id} className="border-t border-slate-50 hover:bg-blue-50/40">{select&&<td className="px-4 py-3"><input aria-label={keyFor(row.original)+' 선택'} type="checkbox" checked={select.checked(row.original)} onChange={()=>select.toggle(row.original)} disabled={select.disabled?.(row.original)}/></td>}{row.getVisibleCells().map(cell=><td key={cell.id} className="px-4 py-3 tabular-nums">{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table>{!table.getRowModel().rows.length&&<Empty title="조건에 맞는 데이터가 없습니다."/>}</div>
 <div className="mt-3 flex items-center justify-between text-xs text-slate-400"><span>{table.getState().pagination.pageIndex+1} / {Math.max(1,table.getPageCount())} 페이지</span><div className="flex gap-2"><Button disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}>이전</Button><Button disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}>다음</Button></div></div></div>;
}
